/**
 * Created by: Hugo Ramalho <ramalho.hg@gmail.com>
 *
 * Created at: 24/03/2025
 **/

export enum STUDIES_OPTION_MENU
{
    TAGS_DICOM = 'TAGS_DICOM',
    DIRECT_VIEWER = 'DIRECT_VIEWER',
    CREATE_RIS_ACCESS = 'CREATE_RIS_ACCESS',
    CREATE_RIS_LINK = 'CREATE_RIS_LINK',
    EXPORT_STUDY = 'EXPORT_STUDY',
    DOWNLOAD_STUDY = 'DOWNLOAD_STUDY',
    DELETE_STUDY = 'DELETE_STUDY',
    DELETE_STUDY_SERIES = 'DELETE_STUDY_SERIES'
}

