FROM node:18-alpine

# Definir diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar package.json e package-lock.json
COPY package*.json ./

# Instalar dependências (inclusive dependências de desenvolvimento)
RUN npm install

# Instalar o Angular CLI globalmente
RUN npm install -g @angular/cli

# Copiar todo o código-fonte do projeto para o contêiner
COPY . .

# Expor a porta usada pelo servidor de desenvolvimento
EXPOSE 4200

# Comando para iniciar o servidor de desenvolvimento
CMD ["npm", "run", "start"]
