/**
 Created by: Hugo Ramalho <ramalho.hg@gmail.com>

 Created at: 01/12/2024
 **/

export interface TagDicom {
    "StudyInstanceUID": string,
    "StudyDate": string,
    "StudyTime": string,
    "StudyModality": string,
    "AccessionNumber": string,
    "StudyID": string,
    "ReferringPhysicianName": string,
    "StudyDescription": string,
    "NumberOfStudyRelatedInstances": string,
    "StudyPriorityID": string,
    "ReasonForStudy": string,
    "RequestingService": string,
    "StudyComments": string,
    "AdmissionID": string,
    "RequestedProcedureID": string,
    "ProcedureCode": string,
    "RequestingPhysicianPhone": string,
    "PatientTransportArrangements": string,
    "SpecificCharacterSet": string,
    "RetrieveAETitle": string,
    "InstanceAvailability": string,
    "RetrieveUrl": string,
    "PatientNameIdeographic": string,
    "PatientNamePhonetic": string,
    "NumberOfStudyRelatedSeries": string,
    "ImagesInAcquisition": string,
    "SOPClassesInStudy": string,
    "IssuerOfPatientId": string,
    "OtherPatientNames": string,
    "PatientComments": string,
    "ModifiedAttributesSequence": string,
    "AttriduteModificationDateTime": string,
    "ModifyingSystem": string,
    "SourceOfPreviousValues": string,
    "ReasonForTheAttributeModification": string,
    "PatientID": string,
    "PatientName": string,
    "PatientBirthDate": string,
    "PatientSex": string,
    "PatientAge": string,
    "PatientSize": string,
    "PatientWeight": string,
    "PatientAddress": string,
    "PatientTelephoneNumbers": string,
    "PatientEmail": string,
    "PatientInsurancePlan": string,
    "EthnicGroup": string,
    "Occupation": string,
    "MedicalAlerts": string,
    "Allergies": string,
    "AdditionalPatientHistory": string,
    "NumberOfPatientRelatedStudies": string
}
